name: satport
recipe: drupal11
config:
  php: '8.3'
  database: 'mariadb:10.6'
  webroot: web
  via: nginx
services:
  appserver:
    overrides:
      ports:
        - "0.0.0.0::80"
        - "0.0.0.0::443"
  rediscache:
    type: redis:7
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
proxy:
  mailhog:
    - mail.satport.lndo.site
env_file:
  - .lando.env