# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://www.{default}/":
    type: upstream
    upstream: "drupal:http"
    cache:
      enabled: true

      # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"

# Redirect all other urls to default. When this project was created, satportinfrastructure.com was the default domain. It is now changed to satport.com
# Below route is to support the older domain in case someone is still using it
"https://{all}/":
    type: redirect
    to: "https://www.{default}/"