# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://www.{default}/":
    type: upstream
    upstream: "drupal:http"
    cache:
      enabled: true
      # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"


# Redirect for the old base domain
"https://satportinfrastructure.com/":
  type: redirect
  to: "https://www.{default}/"

# Redirect for the old www domain
"https://www.satportinfrastructure.com/":
  type: redirect
  to: "https://www.{default}/"